
name: CI/CD with Push and Scheduled Actions

on:
  push:
    branches: [main]

on:
  schedule:
    -cron:‘30 7 * * 5’# every Friday 06:00 UTC

on:
  schedule:
    -cron: ‘* * * * *’

on:
  label:
    types:
      -created

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
